general {
    lock_cmd = pgrep -x hyprlock >/dev/null || hyprlock
    before_sleep_cmd = pidof hyprlock && (hyprlock &) && sleep 5
    after_sleep_cmd = sleep 5 && hyprctl dispatch dpms on
}

# 15 min idle: dim screen
listener {
    timeout = 900
    on-timeout = brightnessctl -s set 10
    on-resume = brightnessctl -r
}

# 20 min idle: lock screen
listener {
    timeout = 1200
    on-timeout = brightnessctl -r && (pidof hyprlock || hyprlock)
}

# 30 min idle: turn screen off
listener {
    timeout = 1800
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# 60 min idle: suspend
listener {
    timeout = 3600
    on-timeout = systemctl suspend
}
